### PR TITLE
Selenium bot

### PR DESCRIPTION
**Pull request by ShravanTandel**

### CODE REVIEW

**Review by Ramadas-Kamat — COMMENTED** [review]
I think its safe to merge. Is the login form written by Sharath or is it yours?

**Comment by ShravanTandel** [comment]
> I think it's safe to merge. Is the login form written by Sharath or is it yours?

No, it's written by me. After we merge the code, Sharath can override the login form

**Comment by Ramadas-Kamat** [comment]
I need to resolve conflicts and will merge it in development branch. That should be fine ig?

**Comment by Ramadas-Kamat** [comment]
Merged your request.

**Pull request closed without merging**
